# Historical companion fixtures for regression tests only; never published.
# Names are overlay stems, native or service-table.
# Every overlay absent from BOOT must appear exactly once here; MENU is shared.
PACKAGE_ROLES = FILES MEDIA DISKTOOLS DEVTOOLS
PACKAGE_FILES = DOSGET DOSWRITE DOSIMAGE DOSPUT EDIT SEARCH AWP AWDATA BINARY2 UNSHRINK UNWRAP SCIIBIN UNSQ FIND FIXTYPES GOTO MDVIEW GUTTEXT TEACHTXT RENAME SYNC MOVE TREE
PACKAGE_MEDIA = IMAGE MUSIC MCS DOSMCS DOSNEWS NEWSPAN NEWSPAGE MCSIMPORT MCSPLAY DOCVIEW VISICALC DGRVIEW EXTASIE ARLEQUIN MACPAINT SHAPES PACKFOT PAINT816 PURPLE LZ4FH PRINTSHOP NEWSROOM NRCLIP GMAGIC FONTVIEW FONTRIX PT3 DUET
PACKAGE_DISKTOOLS = IMGPUT DOS33W DOSREPL NIBCOPY VOLINFO FIXIT REPAIR VOLNAME WIPE BOOTBLK BLKVIEW BLKEDIT DISKCMP IMGCONV MKIMAGE RESCUE UNDELETE
PACKAGE_DEVTOOLS = PASCAL PASCALW PASTEXT SCASM MERLIN LISAV2 CPM CPMW BASLIST DISASM INTBASIC DOSINT DOSBAS CRC IDENT IDREAD IDFORMATS
PACKAGE_VOLUME_FILES = A2FILES
PACKAGE_VOLUME_MEDIA = A2MEDIA
PACKAGE_VOLUME_DISKTOOLS = A2DISKS
PACKAGE_VOLUME_DEVTOOLS = A2DEVTOOLS
PACKAGE_BASIC = DEVTOOLS
PACKAGE_RUNTIMES = BASIC.SYSTEM INTBASIC.SYSTEM
