#!/usr/bin/env python3
"""Stage the XL disk's DEMO folder: one folder per kind of file.

    stage_demo.py DEMO_DIR

DEMO holds one example of everything A2 File Cmd opens, sorted the way the
guide's chapters are: DOCUMENTS, PICTURES (with the HGR album), MUSIC,
ARCHIVES, DISKS, PROGRAMS and FONTS.SHAPES. Most files are generated by
mkdemo.py; the best of CiderPress II's test samples (data/CP2) join the
folder of their kind instead of a folder of their own, and the nine HGR
pages of data/IMGHGR form PICTURES/ALBUM. README.TXT at the top says what
is where and where the borrowed files come from.
"""
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mkdemo

DATA = Path(__file__).resolve().parents[1] / 'data'

# host names as mkdemo.make(full=True) writes them, by folder
GENERATED = {
    'DOCUMENTS': ['SAMPLE.TXT', 'LETTER#1A0000'],
    'PICTURES': ['HGR.RAW.BIN', 'HGR.RLE.BIN', 'DHGR.RAW.BIN', 'DHGR.RLE.BIN'],
    'MUSIC': ['WELCOME.MB.BIN', 'CANON.ED#D5D0E7'],
    'ARCHIVES': ['SAMPLE.SHK', 'SAMPLE.BNY'],
    'DISKS': ['TINY.PO', 'TINY.2MG', 'DISK800.DC#E08005', 'DOS33.DSK'],
    'PROGRAMS': ['HELLO#FC0801'],
}

# the CiderPress II samples kept, by folder (data/CP2 keeps them all for the tests)
BORROWED = {
    'DOCUMENTS': ['DOCS/PRESIDENTS#19C07F', 'DOCS/MATH.QUIZ#1B807B'],
    'PICTURES': ['GRAPHICS/ESCHERWATER.MAC#000000'],
    'ARCHIVES': ['ARCHIVES/SHRINKIT.BSC#040000', 'ARCHIVES/HELLO.AS#E00001'],
    'FONTS.SHAPES': ['GRAPHICS/STANDARD#070000',
                     'GRAPHICS/SHAPETABLE/BBROS.F.STENCIL#066000',
                     'GRAPHICS/SHAPETABLE/SC.SHIP2.SHAPE#064524',
                     'GRAPHICS/SHAPETABLE/DATSTNES.SHAPE1#060800'],
}


def stage(demo):
    demo = Path(demo)
    if demo.exists():
        raise SystemExit(f'{demo} already exists')
    demo.mkdir(parents=True)
    with tempfile.TemporaryDirectory() as tmp:
        flat = mkdemo.make(Path(tmp) / 'flat', full=True)
        made = {p.name for p in flat.iterdir()}
        placed = [n for names in GENERATED.values() for n in names]
        if made != set(placed):
            raise SystemExit(f'mkdemo wrote {sorted(made ^ set(placed))} unplaced')
        for folder, names in GENERATED.items():
            (demo / folder).mkdir(exist_ok=True)
            for name in names:
                shutil.copyfile(flat / name, demo / folder / name)
    for folder, names in BORROWED.items():
        (demo / folder).mkdir(exist_ok=True)
        for name in names:
            shutil.copyfile(DATA / 'CP2' / name, demo / folder / Path(name).name)
    shutil.copytree(DATA / 'IMGHGR', demo / 'PICTURES' / 'ALBUM')
    shutil.copyfile(DATA / 'README.TXT', demo / 'README.TXT')
    return demo


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    stage(sys.argv[1])
