#!/usr/bin/env python3
"""Stage the XL disk's DEMO folder: one folder per kind of file.

    stage_demo.py DEMO_DIR

DEMO holds one example of everything A2 File Cmd opens, sorted the way the
guide's chapters are: DOCUMENTS, PICTURES, MOVIES, MUSIC, ARCHIVES, DISKS,
PROGRAMS and FONTS.SHAPES. Most files are generated by mkdemo.py; the best
of CiderPress II's test samples (data/CP2) join the folder of their kind
instead of a folder of their own; mkdemo_viewers.py adds one file for every
other viewer, so that each viewer A2 File Cmd has opens at least one DEMO
file (tools/test_file_viewers.py checks it through the real classifier),
and mkdemo_take1.py the Take 1 movie, on its DOS 3.3 disk.
README.TXT at the top says what is where and where the borrowed files come
from.

Three rules keep the folder readable:
  - a name is SUBJECT.FORMAT, or what the original program requires (PH.x
    for a Newsroom photo, M.x for a Fantavision movie); a file whose ProDOS
    type already says the format needs no suffix;
  - PICTURES holds pictures: the nine HGR pages of data/IMGHGR are
    PICTURES/ALBUM, and the two colour cards encoded in every picture
    format are PICTURES/CARDS, where the name is the format alone;
  - one file per format: when two files would show the same thing through
    the same viewer (a raw page and its packed twin, a volume and the same
    volume under a 2IMG header), DEMO keeps one. mkdemo.py still makes the
    others for the benches (BENCH_ONLY).
"""
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import mkdemo
import mkdemo_take1
import mkdemo_viewers
import mcs_ref

DATA = Path(__file__).resolve().parents[1] / 'data'

# host names as mkdemo.make(full=True) writes them, by folder
GENERATED = {
    'DOCUMENTS': ['SAMPLE.TXT', 'LETTER#1A0000'],
    'PICTURES/CARDS': ['HGR.RLE.BIN', 'DHGR.RAW.BIN'],
    'MUSIC': ['WELCOME.MB.BIN', 'CANON.ED#D5D0E7'],
    'ARCHIVES': ['SAMPLE.SHK', 'SAMPLE.BNY'],
    'DISKS': ['TINY.PO', 'DISK800.DC#E08005', 'DOS33.DSK'],
    'PROGRAMS': ['HELLO#FC0801'],
}

# made by mkdemo.make(full=True) for the benches, left out of DEMO: the
# album already shows raw HGR pages, HGR.RLE the packed stream, TINY.PO the
# volume TINY.2MG wraps
BENCH_ONLY = {'HGR.RAW.BIN', 'DHGR.RLE.BIN', 'TINY.2MG'}

# the CiderPress II samples kept, by folder (data/CP2 keeps them all for the tests)
BORROWED = {
    'DOCUMENTS': ['DOCS/PRESIDENTS#19C07F', 'DOCS/MATH.QUIZ#1B807B'],
    'PICTURES': ['GRAPHICS/ESCHERWATER.MAC#000000'],
    'ARCHIVES': ['ARCHIVES/SHRINKIT.BSC#040000', 'ARCHIVES/HELLO.AS#E00001'],
    'FONTS.SHAPES': ['GRAPHICS/STANDARD#070000',
                     'GRAPHICS/SHAPETABLE/BBROS.F.STENCIL#066000',
                     'GRAPHICS/SHAPETABLE/SC.SHIP2.SHAPE#064524',
                     'GRAPHICS/SHAPETABLE/DATSTNES.SHAPE1#060800'],
}


def stage(demo):
    demo = Path(demo)
    if demo.exists():
        raise SystemExit(f'{demo} already exists')
    demo.mkdir(parents=True)
    with tempfile.TemporaryDirectory() as tmp:
        flat = mkdemo.make(Path(tmp) / 'flat', full=True)
        made = {p.name for p in flat.iterdir()}
        placed = [n for names in GENERATED.values() for n in names]
        if made != set(placed) | BENCH_ONLY:
            raise SystemExit(f'mkdemo wrote {sorted(made ^ (set(placed) | BENCH_ONLY))} unplaced')
        for folder, names in GENERATED.items():
            (demo / folder).mkdir(parents=True, exist_ok=True)
            for name in names:
                shutil.copyfile(flat / name, demo / folder / name)
    for folder, names in BORROWED.items():
        (demo / folder).mkdir(exist_ok=True)
        for name in names:
            shutil.copyfile(DATA / 'CP2' / name, demo / folder / Path(name).name)
    shutil.copytree(DATA / 'IMGHGR', demo / 'PICTURES' / 'ALBUM')
    viewers = mkdemo_viewers.files()
    viewers['MOVIES'].update(mkdemo_take1.files())
    for folder, items in viewers.items():
        (demo / folder).mkdir(parents=True, exist_ok=True)
        for name, data in items.items():
            if (demo / folder / name).exists():
                raise SystemExit(f'{folder}/{name} placed twice')
            (demo / folder / name).write_bytes(data)
    # TXT metadata keeps Return from executing an unrecognized binary tune.
    # This is an explicit !/MCS demonstration, not an editor .OBJ score.
    (demo / 'MUSIC' / 'DEMO.MCS#040000').write_bytes(mcs_ref.fixture())
    shutil.copyfile(DATA / 'README.TXT', demo / 'README.TXT')
    return demo


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    stage(sys.argv[1])
